### ISSUE TITLE
Rendering full-width without defining a static width

### ISSUE THREAD

**Issue by MickL** [Giphy/giphy-js#183]
In `@giphy/js-components` render functions like `renderGif` and `renderGrid` need a static width. As a feature request I would like to have them be responsive with pure css 100% width, without the need of defining a static width in js, listening to window-resize and rerendering.

**Comment by giannif** [comment]
@MickL this is definitely something we would have included if possible. Our `Grid` require a masonry layout, and there was no way to do masonry with pure css (you can get close, but not quite there).

As far as the regular `Gif` component, I think at some point in the future we can switch to using `srcset` to do rendition selection instead of requiring a fixed width, but I'm not sure if we'd be compromising any of our rendition selection algorithm 

I'll leave this ticket open and we can try to investigate that at some point

**Comment by MickL** [comment]
I understand. Maybe giphy should do the rerendering, tho, not the consumer?

The downside would be that this may add a few more bytes of code to giphy since it may need throttle-debounce or similiar. In my project I entirely use RxJS for things like this so I am fine that I trigger rerendering.

**Comment by giannif** [comment]
@MickL I'd like to make it easier to use but I think the width needs to be defined by the user here when they render, and therefore giphy can't do the rerender. Next time I'm working on this part of the code base I'll take a deeper dive but for now it seems okay. Thanks for the feedback
