### ISSUE TITLE
Node support

### ISSUE THREAD

**Issue by breadadams** [Giphy/giphy-js#58]
I've tried to implement `@giphy/js-fetch-api` in a Node script, but I'm getting errors regarding code that's "browser only" (`window`, `new Headers()`, etc).

Is the library intended to be for client-side JS only? - or is there Node support planned?

**Comment by giannif** [comment]
@breadadams it wasn't a product requirement, but if `headers` is the only issue with node support then we can find a way to do it. In your environment, you can maybe require [isomorphic-fetch](https://www.npmjs.com/package/isomorphic-fetch) before you require our lib. If there are other issues, lmk and I'll see what we can do about `headers`

**Comment by giannif** [comment]
@breadadams released the new packages below that don't have the headers in fetch api, lmk if there are any other blockers for node!

 - @giphy/js-components: 2.4.3
 - @giphy/js-fetch-api: 1.5.3
 - @giphy/react-components: 0.7.3

**Comment by giannif** [comment]
@breadadams I realized the headers are still referenced in our util package, will follow up when I have time to fix this

**Comment by breadadams** [comment]
Ahh of course - no worries @giannif. Thanks for the effort here!

I ended up using the API directly in the end, which works for us as it's only a single request to the search API (you can see it [here](https://github.com/wombak/www-progress/blob/master/scripts/gifs.js)). However I'll be happy to move it over the the SDK once it's available 🙌

**Comment by giannif** [comment]
@breadadams you should be good to go! here's a codesandbox showing it in action: https://codesandbox.io/s/fetch-api-in-express-kwfq8

The fetch api processes gifs after fetching, it normalizes some weirdness in our api responses and also helps us track which endpoint the gifs came from for our metrics. 

If you have any issues lmk!

**Comment by devpascoe** [comment]
Something to look into is React Native support. Unable to get an iOS app running, comment out import { GiphyFetch } from '@giphy/js-fetch-api' and i am working again. Can use urls directly for now.

**Comment by breadadams** [comment]
Thanks @giannif - I'll give it a shot this week!

@devpascoe react-native support would be nice! I'd open a separate issue for it and post the error logs you're getting. I'm sure they'll be able to sort it 😉💪

**Comment by giannif** [comment]
@devpascoe `react-native` support is on the wish list! but not exactly on our roadmap just yet, feel free to create an issue and we can hopefully get started on it

**Comment by budde377** [comment]
@giannif, I might be missing something, but it looks like you're still not supporting node, because you assume that `fetch` is available? I'm getting the error
```
Error: fetch is not defined
    at new FetchError (.../node_modules/@giphy/js-fetch-api/src/fetch-error.ts:5:9)
    at Object.<anonymous> (.../node_modules/@giphy/js-fetch-api/src/request.ts:37:30)
    ...
```
because of a call to fetch here https://github.com/Giphy/giphy-js/blob/master/packages/fetch-api/src/request.ts#L19 .

It might be worth using https://www.npmjs.com/package/isomorphic-fetch or allowing users to pass their own fetch in the `GiphyFetch` constructor?

**Comment by giannif** [comment]
@budde377 I left it up to you to add the polyfill for fetch. In my experience, this is customary for libraries with polyfills. In the [codesandbox](https://codesandbox.io/s/fetch-api-in-express-kwfq8) I listed above, I used `isomorphic-fetch`.  

I think this approach is best, because I wouldn't want to include a polyfill in the package that globally shims anything, it might override something in your application. 

It also keeps the bundle size down

**Comment by breadadams** [comment]
Yeah, the polyfill should be handled at project level - **not** in the Giphy SDK 👍

**Comment by budde377** [comment]
@giannif That makes sense, thanks!

**Comment by davidmm07** [comment]
Works for me in Typescript with API's in Node 

`import fetch from "node-fetch";`
`declare var global: any;`
`global.fetch = fetch;`
