### ISSUE TITLE
How to implement analytics

### ISSUE THREAD

**Issue by alokjkumar** [Giphy/giphy-js#94]
There are three URLs for analytics - at what points do these need to be called? Is loaded called when the search results load or when the result of clicking on the gif is loaded? When is the click URL called vs the sent URL?

Thanks

**Comment by giannif** [comment]
Hello @alokjkumar, analytics are baked in to the components themselves. You don't need to do anything

**Comment by alokjkumar** [comment]
@giannif for the fetch api?

**Comment by giannif** [comment]
@alokjkumar there are no analytics for the fetch api. The components implement analytics since they know when gifs load, are clicked, hovered, etc. 

Implementing your own analytics is technically possible but it's a pretty complex thing to support, can you not use our `@giphy/js-components` on your front end?
